### ISSUE TITLE
forceTableau param not propagated

### ISSUE THREAD

**Issue by Jaxolotl** [datadotworld/tableau-connector#38]
This is mostly an issue for developers, but I wanted you to know it.

If the fit authorization flow runs on the simulator ( the integration is not authorized yet ), the forceTableau param is not propagated on the querystring, therefore the verification fails and the warning message "Open this page from Tableau version 10 or greater to connect a dataset." is displayed.

Steps to repro:

- revoke the authorizations for the testing integration ( you should own it )
- follow the instructions on the Contributing.md to run it on the Tableau simulator
- on prompt, authenticate
- click authorize
- error

Note that if the integration is already authorized, the flow goes elsewhere and the param propagation issue doesn't happen

Bests
Jax

**Comment by rflprr** [comment]
This should be fixed now.
